# Generated by Django 4.2.4 on 2023-08-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pics/dlogo.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
